version: '3.9'

services:
  app:
    container_name: app
    image: marcelofabianov/golang
    restart: always
    working_dir: /app
    build:
      context: ./_docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./_docker/.zshrc:/home/dev/.zshrc
    ports:
      - "8888:8888"
    networks:
      - go_network

networks:
  go_network:
    driver: bridge
