version: '3.9'

services:
  app:
    container_name: app
    restart: always
    build:
      context: ./_docker
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./_docker/zshrc:/home/dev/.zshrc
    ports:
      - "8888:8888"
    networks:
      - go_network

networks:
  go_network:
    driver: bridge
